from pathlib import Path

PROJECT_PATH = Path(__file__).resolve().parent
PARAMS_FILE = PROJECT_PATH.joinpath('assets', 'scraper_parameters.parquet')
AWS_S3_KEY_ENV = "AWS_S3_KEY"
AWS_S3_SECRET_ENV = "AWS_S3_SECRET"
AWS_S3_REGION_ENV = "AWS_S3_REGION"
PROXY_SERVICE_USER_ENV = "PROXY_SERVICE_USER"
PROXY_SERVICE_PASS_ENV = "PROXY_SERVICE_PASS"
CUSTOMER_AWS_KEY = "AWS_S3_KEY_CUSTOMER1"
CUSTOMER_AWS_SECRET = "AWS_S3_SECRET_CUSTOMER1"
CUSTOMER_AWS_REGION = "AWS_S3_REGION_CUSTOMER1"
MONGO_HOST = "MONGO_HOST"
MONGO_USER = "MONGO_USER"
MONGO_PASSWORD = "MONGO_PASSWORD"
SQL_HOST = "SQL_HOST"
SQL_USER = "SQL_USER"
SQL_PASSWORD = "SQL_PASSWORD"
