random_websites_parameters = ['https://www.tableau.com/about/contact',
                              'https://about.google/contact-google/', 'https://www.ibm.com/contact/us/en/',
                              'https://support.microsoft.com/en-us/contactus/', 'https://www.ni.com/en/contact-us.html',
                              'https://www.agilent.com/en/contact-us/page', 'https://www.ford.com/help/contact/',
                              'https://www.shopify.com/blog/contact-us-page',
                              'https://www.accaglobal.com/gb/en/footer-toolbar/contact-us.html',
                              'https://www.census.gov/about/contact-us.html',
                              'https://www.barclays.co.uk/help/contact-us/',
                              'https://www.commerce.gov/about/contact-us', 'https://www.redhat.com/en/contact',
                              'https://www.aerlingus.com/support/customer-care/contact-us/',
                              'https://www.fortinet.com/corporate/about-us/contact-us',
                              'https://www.ssa.gov/agency/contact/',
                              'https://www.uc.pa.gov/Pages/Contact-Us-UC-Benefits-Info.aspx',
                              'https://www.amtrak.com/contact-us', 'https://us.pg.com/contact-us/',
                              'https://www.bankofamerica.com/customer-service/contact-us/',
                              'https://www.fca.org.uk/contact', 'https://www.canada.ca/en/contact.html',
                              'https://www.senate.gov/senators/senators-contact.htm',
                              'https://www.bose.com/en_us/contact_us.html',
                              'https://owners.hyundaiusa.com/us/en/contact-us.html',
                              'https://www.revenue.ie/en/contact-us/index.aspx',
                              'https://www.toronto.ca/home/contact-us/',
                              'https://www.fidelity.com/customer-service/contact-us',
                              'https://www.indiapost.gov.in/VAS/Pages/Content/ContactUs.aspx',
                              'https://www.samaritans.org/how-we-can-help/contact-samaritan/',
                              'https://br.godaddy.com/help/contact-us',
                              'https://www.ncdot.gov/contact/Pages/default.aspx',
                              'https://survicate.com/blog/create-perfect-contact-us-page/',
                              'https://helpcenter.trendmicro.com/en-us/contact-support/',
                              'https://www.youtube.com/t/contact_us',
                              'https://www.wordstream.com/blog/ws/2015/03/11/contact-us-page',
                              'https://www.ato.gov.au/about-ato/contact-us/',
                              'https://home.pearsonvue.com/Contact-Us.aspx',
                              'https://www.adp.com/contact-us/customer-service.aspx',
                              'https://www.ird.govt.nz/contactus', 'https://www.nestle.com/info/contactus/contactus',
                              'https://www.service.nsw.gov.au/contact-us', 'https://ico.org.uk/global/contact-us/',
                              'https://www.cbp.gov/contact', 'https://www.whitehouse.gov/contact/',
                              'https://www.atlassian.com/company/contact',
                              'https://www.wellsfargo.com/help/contact-us/', 'https://www.jotform.com/contact/',
                              'https://www.manulife.ca/personal/support/contact-us.html',
                              'https://www.verizon.com/support/contact-us/',
                              'https://www.thomsonreuters.com/en/contact-us.html', 'https://www.qld.gov.au/contact-us',
                              'https://www.refinitiv.com/en/contact-us', 'https://www.treasurydirect.gov/contact-us/',
                              'https://www.justice.gov/contact-us', 'https://zyro.com/blog/contact-us-page-examples/',
                              'https://www.gov.br/anvisa/pt-br/english/contact-us', 'https://support.apple.com/contact',
                              'https://wpforms.com/how-to-make-an-outstanding-contact-us-page-with-8-examples/',
                              'https://www.ica.gov.sg/contact-us', 'https://www.nzta.govt.nz/contact-us/',
                              'https://www.citizensadvice.org.uk/about-us/contact-us/contact-us/contact-us/',
                              'https://travel.state.gov/content/travel/en/contact-us.html',
                              'https://www.zendesk.com.br/blog/contact-us-page/',
                              'https://blog.hubspot.com/service/best-contact-us-pages',
                              'https://www.linguee.com.br/espanhol-portugues/traducao/contact+us.html',
                              'https://www.impactplus.com/blog/best-contact-us-page-examples',
                              'https://www.wolterskluwer.com/en/solutions/uptodate/contact-us',
                              'https://www.iras.gov.sg/contact-us',
                              'https://www.condornaoletal.com.br/contact-us/?lang=en']
